<script src="<?= BASE_URL ?>/assets/vendor/jquery/jquery.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/php-email-form/validate.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/jquery-sticky/jquery.sticky.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/venobox/venobox.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/aos/aos.js"></script>
